### ISSUE TITLE
summoner info icons in overlay

### ISSUE THREAD

**Issue by MarlonWelter** [lmachens/lol-trophy-hunter#66]
Info icons next to summoner in overlay,
 e.g.: "Killer" =>  Summoner often has most kills in the game.

If we use information relative to other players in the match (like most kills/deaths/assists) we could say often means sth like "in more than 30% of games".

Possible relative features:
Most Kills
Most/Least Deaths
Most Damage
Most Cs
FirstBlood
FirstTurret
Most Turret Dmg

**Comment by lmachens** [comment]
![image](https://cloud.githubusercontent.com/assets/10058950/26655824/c798e9d4-465c-11e7-83c2-4e0000c7ca2d.png)

ToDo:
- Maximum Minions looks broken
- Set threshold for badge like 20% of analysed matches (maybe depending on feature?)
